// <auto-generated />
namespace LearningPlatform.Data.EntityFramework.SurveysDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBackgroundStyleFieldIntoTheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBackgroundStyleFieldIntoTheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201707170931532_AddBackgroundStyleFieldIntoTheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
