// <auto-generated />
namespace LearningPlatform.Data.EntityFramework.SurveysDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddStepAndDecimalPlacesValidationForNumericQuestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStepAndDecimalPlacesValidationForNumericQuestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201705090140084_AddStepAndDecimalPlacesValidationForNumericQuestion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
