// <auto-generated />
namespace LearningPlatform.Data.EntityFramework.SurveysDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateDiscriminatorAndRemoveUnusedElementForReportElement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateDiscriminatorAndRemoveUnusedElementForReportElement));
        
        string IMigrationMetadata.Id
        {
            get { return "201703270700558_UpdateDiscriminatorAndRemoveUnusedElementForReportElement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
