// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LearningPlatform.Specs.Features.RandomDataGenerator
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RandomDataGeneratorFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RandomDataGenerator.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RandomDataGenerator", "\tIn order to avoid mistakes in the survey and to generate test data\r\n\tAs a survey" +
                    " creator\r\n\tI want to be able to generate random data for the survey.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "RandomDataGenerator")))
            {
                LearningPlatform.Specs.Features.RandomDataGenerator.RandomDataGeneratorFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Random Generator")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "RandomDataGenerator")]
        public virtual void RandomGenerator()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Random Generator", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have a survey for random data generation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("I start random data generator", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "SurveyId",
                        "RespondentId",
                        "QuestionName",
                        "Alias",
                        "AnswerType",
                        "IntegerAnswer",
                        "DoubleAnswer",
                        "DateTimeAnswer",
                        "TextAnswer"});
            table1.AddRow(new string[] {
                        "1",
                        "000000000000000000000001",
                        "1",
                        "cars",
                        "bmw",
                        "Multi",
                        "0",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "2",
                        "000000000000000000000001",
                        "1",
                        "cars",
                        "mercedes",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "3",
                        "000000000000000000000001",
                        "1",
                        "cars",
                        "ford",
                        "Multi",
                        "0",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "4",
                        "000000000000000000000001",
                        "1",
                        "cars",
                        "tesla",
                        "Multi",
                        "0",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "5",
                        "000000000000000000000001",
                        "1",
                        "cars_fav",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "6",
                        "000000000000000000000001",
                        "1",
                        "name",
                        "",
                        "Open",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "7",
                        "000000000000000000000001",
                        "1",
                        "rate_bmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "4"});
            table1.AddRow(new string[] {
                        "8",
                        "000000000000000000000001",
                        "1",
                        "rate_mercedes",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "3"});
            table1.AddRow(new string[] {
                        "9",
                        "000000000000000000000001",
                        "1",
                        "rate_ford",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "1"});
            table1.AddRow(new string[] {
                        "10",
                        "000000000000000000000001",
                        "1",
                        "rateBmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "5"});
            table1.AddRow(new string[] {
                        "11",
                        "000000000000000000000001",
                        "1",
                        "numeric",
                        "",
                        "Number",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "12",
                        "000000000000000000000001",
                        "1",
                        "date",
                        "",
                        "Date",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "13",
                        "000000000000000000000001",
                        "2",
                        "cars",
                        "bmw",
                        "Multi",
                        "0",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "14",
                        "000000000000000000000001",
                        "2",
                        "cars",
                        "mercedes",
                        "Multi",
                        "0",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "15",
                        "000000000000000000000001",
                        "2",
                        "cars",
                        "ford",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "16",
                        "000000000000000000000001",
                        "2",
                        "cars",
                        "tesla",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "17",
                        "000000000000000000000001",
                        "2",
                        "cars_fav",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "18",
                        "000000000000000000000001",
                        "2",
                        "name",
                        "",
                        "Open",
                        "",
                        "",
                        "",
                        "Cupidatat."});
            table1.AddRow(new string[] {
                        "19",
                        "000000000000000000000001",
                        "2",
                        "rate_bmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "20",
                        "000000000000000000000001",
                        "2",
                        "rate_mercedes",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "4"});
            table1.AddRow(new string[] {
                        "21",
                        "000000000000000000000001",
                        "2",
                        "rate_ford",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "22",
                        "000000000000000000000001",
                        "2",
                        "rateBmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "23",
                        "000000000000000000000001",
                        "2",
                        "numeric",
                        "",
                        "Number",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "24",
                        "000000000000000000000001",
                        "2",
                        "date",
                        "",
                        "Date",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "25",
                        "000000000000000000000001",
                        "3",
                        "cars",
                        "bmw",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "26",
                        "000000000000000000000001",
                        "3",
                        "cars",
                        "mercedes",
                        "Multi",
                        "0",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "27",
                        "000000000000000000000001",
                        "3",
                        "cars",
                        "ford",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "28",
                        "000000000000000000000001",
                        "3",
                        "cars",
                        "tesla",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "29",
                        "000000000000000000000001",
                        "3",
                        "cars_fav",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "30",
                        "000000000000000000000001",
                        "3",
                        "name",
                        "",
                        "Open",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "31",
                        "000000000000000000000001",
                        "3",
                        "rate_bmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "32",
                        "000000000000000000000001",
                        "3",
                        "rate_mercedes",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "33",
                        "000000000000000000000001",
                        "3",
                        "rate_ford",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "2"});
            table1.AddRow(new string[] {
                        "34",
                        "000000000000000000000001",
                        "3",
                        "rateBmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "35",
                        "000000000000000000000001",
                        "3",
                        "numeric",
                        "",
                        "Number",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "36",
                        "000000000000000000000001",
                        "3",
                        "date",
                        "",
                        "Date",
                        "",
                        "",
                        "02/08/2000 08:31:10",
                        ""});
            table1.AddRow(new string[] {
                        "37",
                        "000000000000000000000001",
                        "4",
                        "cars",
                        "bmw",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "38",
                        "000000000000000000000001",
                        "4",
                        "cars",
                        "mercedes",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "39",
                        "000000000000000000000001",
                        "4",
                        "cars",
                        "ford",
                        "Multi",
                        "0",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "40",
                        "000000000000000000000001",
                        "4",
                        "cars",
                        "tesla",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "41",
                        "000000000000000000000001",
                        "4",
                        "cars_fav",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "tesla"});
            table1.AddRow(new string[] {
                        "42",
                        "000000000000000000000001",
                        "4",
                        "name",
                        "",
                        "Open",
                        "",
                        "",
                        "",
                        "Do."});
            table1.AddRow(new string[] {
                        "43",
                        "000000000000000000000001",
                        "4",
                        "rate_bmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "2"});
            table1.AddRow(new string[] {
                        "44",
                        "000000000000000000000001",
                        "4",
                        "rate_mercedes",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "45",
                        "000000000000000000000001",
                        "4",
                        "rate_ford",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "4"});
            table1.AddRow(new string[] {
                        "46",
                        "000000000000000000000001",
                        "4",
                        "rateBmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "47",
                        "000000000000000000000001",
                        "4",
                        "numeric",
                        "",
                        "Number",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "48",
                        "000000000000000000000001",
                        "4",
                        "date",
                        "",
                        "Date",
                        "",
                        "",
                        "02/08/1997 04:25:57",
                        ""});
            table1.AddRow(new string[] {
                        "49",
                        "000000000000000000000001",
                        "5",
                        "cars",
                        "bmw",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "50",
                        "000000000000000000000001",
                        "5",
                        "cars",
                        "mercedes",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "51",
                        "000000000000000000000001",
                        "5",
                        "cars",
                        "ford",
                        "Multi",
                        "0",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "52",
                        "000000000000000000000001",
                        "5",
                        "cars",
                        "tesla",
                        "Multi",
                        "1",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "53",
                        "000000000000000000000001",
                        "5",
                        "cars_fav",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        "bmw"});
            table1.AddRow(new string[] {
                        "54",
                        "000000000000000000000001",
                        "5",
                        "name",
                        "",
                        "Open",
                        "",
                        "",
                        "",
                        "Ullamco dolor voluptate."});
            table1.AddRow(new string[] {
                        "55",
                        "000000000000000000000001",
                        "5",
                        "rate_bmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "56",
                        "000000000000000000000001",
                        "5",
                        "rate_mercedes",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "57",
                        "000000000000000000000001",
                        "5",
                        "rate_ford",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "58",
                        "000000000000000000000001",
                        "5",
                        "rateBmw",
                        "",
                        "Single",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "59",
                        "000000000000000000000001",
                        "5",
                        "numeric",
                        "",
                        "Number",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "60",
                        "000000000000000000000001",
                        "5",
                        "date",
                        "",
                        "Date",
                        "",
                        "",
                        "07/20/1995 21:13:52",
                        ""});
#line 10
 testRunner.Then("the database should have the following responses", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
