// <auto-generated />
namespace LearningPlatform.Data.EntityFramework.ResponsesDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IdFieldsAsString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdFieldsAsString));
        
        string IMigrationMetadata.Id
        {
            get { return "201704240843474_IdFieldsAsString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
